# stage 1: build
FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

# Declare build arguments
ARG VITE_GEMINI_API_KEY
ARG VITE_SOCKET_URL
ARG VITE_TURN_URLS
ARG VITE_TURN_USERNAME
ARG VITE_TURN_CREDENTIAL
ARG VITE_FORCE_TURN_RELAY
ARG VITE_ENABLE_STREAM_VIDEO
ARG VITE_MEDIA_BASE_URL

# Set environment variables for the build process
ENV VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY
ENV VITE_SOCKET_URL=$VITE_SOCKET_URL
ENV VITE_TURN_URLS=$VITE_TURN_URLS
ENV VITE_TURN_USERNAME=$VITE_TURN_USERNAME
ENV VITE_TURN_CREDENTIAL=$VITE_TURN_CREDENTIAL
ENV VITE_FORCE_TURN_RELAY=$VITE_FORCE_TURN_RELAY
ENV VITE_ENABLE_STREAM_VIDEO=$VITE_ENABLE_STREAM_VIDEO
ENV VITE_MEDIA_BASE_URL=$VITE_MEDIA_BASE_URL

COPY . .
RUN npm run build

# stage 2: extract dist
FROM alpine:latest

WORKDIR /app

COPY --from=build /app/dist ./dist