name: Deploy Orion Chat Web

on:
  push:
    branches:
      - develop #staging
      - main #production
jobs:
    deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        steps:
            # 1. checkout code
            - name: Checkout
              uses: actions/checkout@v3

            # 2. build bằng docker
            - name: Build Docker image
              run: docker build -t orion-chat-web .

            - name: Extract dist
              run: |
                    docker create --name temp orion-chat-web
                    docker cp temp:/app/dist ./dist
                    docker rm temp

            # 3. setup aws
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-southeast-1

            # staging
            - name: Deploy to S3 (staging)
              if: github.ref == 'refs/heads/develop'
              run: |
                aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_STAGING }} --delete

            - name: Invalidate CloudFront (staging)
              if: github.ref == 'refs/heads/develop'
              run: |
                aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID_STAGING }} \
                    --paths "/*"

            # production
            - name: Deploy to S3 (prod)
              if: github.ref == 'refs/heads/main'
              run: |
                aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_PROD }} \
                  --delete \
                  --cache-control "public, max-age=31536000" \

            - name: Invalidate CloudFront (prod)
              if: github.ref == 'refs/heads/main'
              run: |
                aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID_PROD }} \
                    --paths "/*"